# Generated by Django 5.0.4 on 2024-05-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_brand_perma_name_remove_device_perma_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PUT', 'PUT')], default='GET'),
        ),
        migrations.AddField(
            model_name='action',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='protocol',
            field=models.CharField(choices=[('MQTT', 'MQTT'), ('HTTP', 'HTTP')], default='HTTP'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
