# Generated by Django 5.0.4 on 2024-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_action_method_action_path_action_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brand',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='prefix',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
    ]
