# Generated by Django 5.0.4 on 2024-05-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_action_name_alter_brand_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
