# Generated by Django 5.0.4 on 2024-05-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_action_description_brand_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='prefix',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
